---

- block:

  - name: install apache
    apt:
      name: "{{ packages }}"
      state: latest
      dpkg_options: 'force-confnew,force-confdef'
      autoclean: yes
      autoremove: yes
      update_cache: yes
      cache_valid_time: 3600
    vars:
      packages:
      - apache2

  - name: add mailhog proxy config
    template:
      src: mailhog.apache.conf
      dest: /etc/apache2/sites-available/mailhog.conf
      owner: root
      group: root
      mode: 0644

  - name: enable rewrite module
    apache2_module:
      state: present
      name: rewrite

  - name: enable proxy module
    apache2_module:
      state: present
      name: proxy

  - name: enable proxy_balancer module
    apache2_module:
      state: present
      name: proxy_balancer

  - name: enable proxy_http module
    apache2_module:
      state: present
      name: proxy_http

  - name: enable proxy_http module
    apache2_module:
      state: present
      name: proxy_wstunnel

  - name: a2ensite mail
    command: a2ensite mailhog.conf

  - name: restart apache2
    systemd:
      name: apache2
      state: restarted

  when: mailhog_proxy_apache|bool and mailhog_proxy_domain is defined

...
