---
- name: create mailhog directory
  file:
    path: "{{ mailhog_path }}"
    state: directory
    mode: 0644

- name: Download MailHog
  get_url:
    url: "https://github.com/mailhog/MailHog/releases/download/{{ mailhog_release }}/MailHog_linux_amd64"
    dest: "{{ mailhog_path }}/mailhog"
    mode: 0755

- name: add mailhog systemd unit file
  template:
    src: mailhog.service
    dest: /etc/systemd/system/mailhog.service
    mode: 0644

- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: enable mailhog
  systemd:
    name: mailhog
    enabled: yes

- name: start mailhog
  systemd:
    name: mailhog
    state: started

- name: setup apache proxy
  include: apache.yml
  when: mailhog_proxy_apache|bool

- name: setup nginx proxy
  include: nginx.yml
  when: mailhog_proxy_nginx|bool

...
